pod "public-works", :path => "../public-works.podspec"
pod 'AFNetworking'

link_with ['Public Works', 'Public WorksTests']

target :unit_tests, :exclusive => true do
  link_with 'Public WorksTests'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end

xcodeproj 'Public Works/Public Works.xcodeproj'

# target "Demo" do
# end

# target "DemoTests" do
# end
