pod "public-works", :path => "../public-works.podspec"
pod 'NSObject-ObjectMap'
pod 'AFNetworking'

link_with ['Public Works', 'Public WorksTests']

xcodeproj 'Public Works/Public Works.xcodeproj'

# target "Demo" do
# end

# target "DemoTests" do
# end
